// lib/catalog.js
export const products = [
  {
    id: "P-001",
    title: "Prompt Business TH Pack 1",
    tagline: "คำอธิบายสั้น",
    category: "Prompt Pack",
    level: "Pro",
    price: 990,
    originalPrice: 1990,
    rating: 4.9,
    sales: 123,
    image: "/images/p001-cover.webp",
    includes: ["100 Prompts", "PDF + DOCX + MD"],
    files: [".pdf", ".docx", ".md"],
    download: "/products/P-001.zip",
    stripe: "",
    line: "",
    promptpayQR: "/qr-promptpay.png",
  },
  {
    id: "P-002",
    title: "Prompt Business TH Pack 2",
    tagline: "คำอธิบาย…",
    category: "Prompt Pack",
    level: "Pro",
    price: 1490,
    originalPrice: 2990,
    rating: 4.8,
    sales: 200,
    image: "/images/p002-cover.webp",
    includes: ["100 Prompts", "PDF + DOCX + MD"],
    files: [".pdf", ".docx", ".md"],
    download: "/products/P-002.zip",
    stripe: "",
    line: "",
    promptpayQR: "/qr-promptpay.png",
  },
  {
    id: "P-003",
    title: "Prompt Business TH Pack 3",
    tagline: "คำอธิบาย…",
    category: "Prompt Pack",
    level: "Pro",
    price: 2490,
    originalPrice: 4990,
    rating: 4.7,
    sales: 99,
    image: "/images/p003-cover.webp",
    includes: ["100 Prompts", "PDF + DOCX + MD"],
    files: [".pdf", ".docx", ".md"],
    download: "/products/P-003.zip",
    stripe: "",
    line: "",
    promptpayQR: "/qr-promptpay.png",
  },
];

export const byId = Object.fromEntries(products.map(p => [p.id, p]));
