name: Catalog CI

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    # รันทุกวัน 03:00 เอเชีย/กรุงเทพฯ (UTC+7) = 20:00 UTC ของวันก่อนหน้า
    - cron: '0 20 * * *'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Update FX rates
        run: npm run update:rates

      - name: Verify catalog (strict)
        run: node scripts/verify-catalog.mjs --strict

      - name: Smoke test
        run: node scripts/smoke.mjs

      # ถ้าต้องการ commit rates.json ที่อัปเดตกลับ repo ให้ปลดคอมเมนต์ด้านล่าง
      # - name: Commit updated rates.json
      #   if: ${{ success() }}
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add public/catalog/rates.json
      #     git commit -m "chore: update rates.json [skip ci]" || echo "No changes"
      #     git push
